# This is a basic workflow that is manually triggered

name: Manual workflow for tags

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tagId:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'tag to create'
        # Input has to be provided for the workflow to run
        required: true
      branch:
        default: 'BABEL_2_X_DEV'
        required: true
        description: 'branch where to create the tag'
      commit:
        required: false
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create_tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.branch}}
          fetch-depth: 0
      - name: testing
        run: |
          echo $GITHUB_SHA
          git rev-parse HEAD
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{github.event.inputs.tagId}}
          commit_sha: ${{github.event.inputs.commit}}
          
