# This is a basic workflow that is manually triggered

name: Manual workflow for tags

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tagId:
        required: true
      message:
        required: true
      commit_hash:
        required: false
      # branch:
      #   default: 'BABEL_2_X_DEV'
      #   required: false
#         description: 'branch where to create the tag'

        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create_tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          # ref: ${{github.event.inputs.branch}}
          fetch-depth: 0
      - name: Check message
        run: |
            echo ${{github.event.inputs.message}}
      - name: Run create-tag script
        if: ${{github.event.inputs.commit_hash == ''}} 
        run: |
            chmod +x ./create-tag.sh
            export message=${github.event.inputs.message}
            echo "$message"
            ./create-tag.sh -t ${{github.event.inputs.tagId}} -m ${{github.event.inputs.message}}
      - name: Run create-tag script when commit hash is provided
        if: ${{github.event.inputs.commit_hash != ''}} 
        run: |
            chmod +x ./create-tag.sh
            export message=${{github.event.inputs.message}}
            echo "$message"
            ./create-tag.sh -c ${{github.event.inputs.commit_hash}} -t ${{github.event.inputs.tagId}} -m ${{github.event.inputs.message}}
            
      - name: Run commands
        run: |
            echo These are the files present in here
            ls -a
        
